plugins {
    id 'java'
    id 'application'
    id 'jacoco'
    id 'checkstyle'
    id 'org.springframework.boot' version '3.5.10'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'gg.jte.gradle' version '3.1.16'
    id 'com.diffplug.spotless' version '7.0.2'
    id 'org.openapi.generator' version '7.1.0'
}
spotless {
    java {
        target 'src/**/*.java'
        targetExclude 'build/**', 'src/main/generated/**', 'src/test/generated/**'
        eclipse('4.31').configFile('config/spotless/eclipse-java-formatter.xml')
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

group = 'ru.mentee.power'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/milestone' }
    gradlePluginPortal()
}

ext {
    junitVersion = '5.11.0'
    assertjVersion = '3.26.3'
    lombokVersion = '1.18.40'
    springBootVersion = '3.5.10'
    validationApiVersion = '3.1.0'
    hibernateValidatorVersion = '8.0.2.Final'
    liquibaseVersion = '4.25.0'
    mapstructVersion = '1.6.3'
    lombokMapstructBindingVersion = '0.2.0'
    openApiGeneratorVersion = '7.1.0'
    springdocVersion = '2.3.0'
}

dependencies {
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    implementation "org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}"

    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5.21.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.21.0'
    testImplementation 'org.apache.tomcat.embed:tomcat-embed-core:10.1.28'
    testImplementation 'org.apache.tomcat.embed:tomcat-embed-websocket:10.1.28'
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    implementation 'gg.jte:jte-spring-boot-starter-3:3.1.16'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation "jakarta.validation:jakarta.validation-api:${validationApiVersion}"
    implementation "org.hibernate.validator:hibernate-validator:${hibernateValidatorVersion}"

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation "org.liquibase:liquibase-core"

    implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"
    
    runtimeOnly 'org.postgresql:postgresql'

    testRuntimeOnly 'com.h2database:h2:2.3.232'

    testImplementation 'org.assertj:assertj-core:3.24.2'

    testImplementation 'org.wiremock:wiremock-standalone:3.4.2'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign:4.1.0'
    implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.2.0'
    implementation 'io.github.resilience4j:resilience4j-feign:2.2.0'

    implementation "org.springframework.boot:spring-boot-starter-validation"

    implementation 'org.openapitools:jackson-databind-nullable:0.2.6'
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9")
}

openApiGenerate {
    generatorName = "spring"
    inputSpec = "${rootProject.projectDir}".toString().replace('\\', '/') + "/src/main/resources/api/api-spec.yaml"
    outputDir = "${buildDir}/generated".toString().replace('\\', '/')
    apiPackage = "ru.mentee.power.crm.spring.rest.generated"
    modelPackage = "ru.mentee.power.crm.spring.dto.generated"
    configOptions = [
            interfaceOnly: "true",
            useTags: "true",
            dateLibrary: "java8",
            useSpringBoot3: "true",
            documentationProvider: "none"
    ]
}

sourceSets {
    main {
        java {
            srcDir "${buildDir}/generated/src/main/java"
        }
    }
}
compileJava.dependsOn tasks.openApiGenerate

tasks.withType(JavaCompile) {
    options.compilerArgs += [
            '-Amapstruct.defaultComponentModel=spring',
            '-Amapstruct.unmappedTargetPolicy=ERROR'
    ]
}

tasks.withType(Checkstyle) {
    excludes = [
            'ru/mentee/power/crm/spring/dto/generated/**',
            'ru/mentee/power/crm/spring/rest/generated/**',
            'ru/mentee/power/crm/spring/rest/problematic/InviteeController.java'
    ]

    reports {
        html.required = true
    }
}
test {
    useJUnitPlatform()
}

checkstyle {
    configDirectory = file("config/checkstyle")
    configFile = file("config/checkstyle/checkstyle.xml")
    toolVersion = "10.12.0"
}

sourceSets {
    main {
        java {
            srcDirs += "$buildDir/generated/sources/jte/main"
        }
    }
}

application {
    mainClass = 'ru.mentee.power.crm.Application'
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jte {
    sourceDirectory = file('src/main/resources/jte').toPath()
    contentType = gg.jte.ContentType.Html
    binaryStaticContent = false
}
jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.7
            }
        }
    }
}
